// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('fs')
const { platform, arch } = process
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./rookie_cookies.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-android-arm64')
        const bindingPackageVersion = require('rookie-cookies-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./rookie_cookies.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-android-arm-eabi')
        const bindingPackageVersion = require('rookie-cookies-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
        return require('./rookie_cookies.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-win32-x64-gnu')
        const bindingPackageVersion = require('rookie-cookies-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./rookie_cookies.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-win32-x64-msvc')
        const bindingPackageVersion = require('rookie-cookies-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./rookie_cookies.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-win32-ia32-msvc')
        const bindingPackageVersion = require('rookie-cookies-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./rookie_cookies.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-win32-arm64-msvc')
        const bindingPackageVersion = require('rookie-cookies-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./rookie_cookies.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('rookie-cookies-darwin-universal')
      const bindingPackageVersion = require('rookie-cookies-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./rookie_cookies.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-darwin-x64')
        const bindingPackageVersion = require('rookie-cookies-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./rookie_cookies.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-darwin-arm64')
        const bindingPackageVersion = require('rookie-cookies-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./rookie_cookies.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-freebsd-x64')
        const bindingPackageVersion = require('rookie-cookies-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./rookie_cookies.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-freebsd-arm64')
        const bindingPackageVersion = require('rookie-cookies-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./rookie_cookies.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('rookie-cookies-linux-x64-musl')
          const bindingPackageVersion = require('rookie-cookies-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./rookie_cookies.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('rookie-cookies-linux-x64-gnu')
          const bindingPackageVersion = require('rookie-cookies-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./rookie_cookies.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('rookie-cookies-linux-arm64-musl')
          const bindingPackageVersion = require('rookie-cookies-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./rookie_cookies.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('rookie-cookies-linux-arm64-gnu')
          const bindingPackageVersion = require('rookie-cookies-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./rookie_cookies.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('rookie-cookies-linux-arm-musleabihf')
          const bindingPackageVersion = require('rookie-cookies-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./rookie_cookies.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('rookie-cookies-linux-arm-gnueabihf')
          const bindingPackageVersion = require('rookie-cookies-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./rookie_cookies.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('rookie-cookies-linux-loong64-musl')
          const bindingPackageVersion = require('rookie-cookies-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./rookie_cookies.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('rookie-cookies-linux-loong64-gnu')
          const bindingPackageVersion = require('rookie-cookies-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./rookie_cookies.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('rookie-cookies-linux-riscv64-musl')
          const bindingPackageVersion = require('rookie-cookies-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./rookie_cookies.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('rookie-cookies-linux-riscv64-gnu')
          const bindingPackageVersion = require('rookie-cookies-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./rookie_cookies.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-linux-ppc64-gnu')
        const bindingPackageVersion = require('rookie-cookies-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./rookie_cookies.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-linux-s390x-gnu')
        const bindingPackageVersion = require('rookie-cookies-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./rookie_cookies.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-openharmony-arm64')
        const bindingPackageVersion = require('rookie-cookies-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./rookie_cookies.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-openharmony-x64')
        const bindingPackageVersion = require('rookie-cookies-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./rookie_cookies.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('rookie-cookies-openharmony-arm')
        const bindingPackageVersion = require('rookie-cookies-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.6.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

function createLoadErrorChain(errors) {
  return errors.reduce((previous, current) => {
    let message
    try {
      message =
        current && typeof current.message === 'string'
          ? current.message
          : String(current)
    } catch {
      message = 'Unknown error'
    }
    const error = new Error(message)
    error.cause = previous
    return error
  }, null)
}

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → prefer WASI, but retain native as a lazy fallback
//   'error'                  → require WASI without initializing a native fallback
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
//
// NAPI_RS_WASI_FLAVOR selects one exact generated flavor and implies strict
// WASI loading. It never crosses into another flavor or falls back to native.
const __napiWasiFlavors = ["wasm32-wasi"]
const __napiWasiFlavor = process.env.NAPI_RS_WASI_FLAVOR
const __napiWasiFlavorRequested =
  typeof __napiWasiFlavor === 'string' && __napiWasiFlavor.length > 0
if (
  __napiWasiFlavorRequested &&
  __napiWasiFlavors.indexOf(__napiWasiFlavor) === -1
) {
  throw new Error(
    'Unsupported WASI flavor "' +
      __napiWasiFlavor +
      '". Available flavors: ' +
      __napiWasiFlavors.join(', '),
  )
}
const forceWasiError = process.env.NAPI_RS_FORCE_WASI === 'error'
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' ||
  forceWasiError ||
  __napiWasiFlavorRequested

if (!forceWasi) {
  nativeBinding = requireNative()
}

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingLoaded = false
  const wasiBindingErrors = []
  const __napiWasiResolveCandidate = (specifier, isPackage, localArtifacts) => {
    try {
      require.resolve(specifier)
    } catch (resolveError) {
      if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
        throw resolveError
      }
      if (isPackage) {
        try {
          require.resolve(specifier + '/package.json')
        } catch (packageError) {
          if (packageError && packageError.code === 'MODULE_NOT_FOUND') {
            return resolveError
          }
          // An exports restriction proves the package exists even when its
          // package.json is not public. Preserve the root resolution failure.
          throw resolveError
        }
        // The package exists but its main/export target is broken.
        throw resolveError
      }
      return resolveError
    }
    if (localArtifacts) {
      let artifactError = null
      for (let i = 0; i < localArtifacts.length; i++) {
        try {
          require.resolve(localArtifacts[i])
          return null
        } catch (resolveError) {
          if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
            throw resolveError
          }
          artifactError = resolveError
        }
      }
      return artifactError
    }
    return null
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('./rookie_cookies.wasi.cjs', false, ["./rookie_cookies.wasm32-wasi.debug.wasm","./rookie_cookies.wasm32-wasi.wasm"])
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        wasiBinding = require('./rookie_cookies.wasi.cjs')
        nativeBinding = wasiBinding
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('rookie-cookies-wasm32-wasi', true, undefined)
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        if (process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          const bindingPackageVersion = require('rookie-cookies-wasm32-wasi/package.json').version
          if (bindingPackageVersion !== '0.6.0') {
            throw new Error(`WASI binding package version mismatch, expected 0.6.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
        }
        wasiBinding = require('rookie-cookies-wasm32-wasi')
        nativeBinding = wasiBinding
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (
    !wasiBindingLoaded &&
    forceWasi &&
    !forceWasiError &&
    !__napiWasiFlavorRequested
  ) {
    nativeBinding = requireNative()
  }
  if ((forceWasiError || __napiWasiFlavorRequested) && !wasiBindingLoaded) {
    const error = new Error(
      __napiWasiFlavorRequested
        ? 'WASI binding for flavor "' + __napiWasiFlavor + '" not found'
        : 'WASI binding not found and NAPI_RS_FORCE_WASI is set to error',
    )
    error.cause = createLoadErrorChain(wasiBindingErrors)
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = createLoadErrorChain(loadErrors)
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

const { CancellationHandle, version, toNetscape, anyBrowser, extractFromPath, cookiesFromPath, chromiumCookiesFromPath, chromiumCookiesFromPathDetailed, firefox, firefoxProfiles, firefoxProfile, zen, librewolf, cachy, chrome, chromeProfiles, chromeProfile, brave, arc, edge, opera, operaGx, chromium, vivaldi, firefoxBased, firefoxBasedDetailed, supportedBrowsers, browserProfiles, browserReport, loadReport, load, octoBrowser, internetExplorer, safari, chromiumBased, chromiumBasedDetailed, read, jar, ReadResult, profiles, report, fromPath, testWorkerPanic } = nativeBinding

function requiredNative(nativeFunction, name) {
  if (typeof nativeFunction !== 'function') {
    throw new TypeError(`Expected a native binding function: ${name}`)
  }
  return nativeFunction
}

const structuredErrorPrefix = '__ROOKIE_ERROR_V1__'
const requestStatusCodes = new Set([
  'InvalidArg',
  'ObjectExpected',
  'StringExpected',
  'NameExpected',
  'FunctionExpected',
  'NumberExpected',
  'BooleanExpected',
  'ArrayExpected',
  'BigintExpected',
  'DateExpected',
  'ArrayBufferExpected',
  'DetachableArraybufferExpected',
])

function decorateNativeError(error) {
  if (!error || (typeof error !== 'object' && typeof error !== 'function')) {
    return error
  }

  let details
  if (
    typeof error.message === 'string'
    && error.message.startsWith(structuredErrorPrefix)
  ) {
    try {
      details = JSON.parse(error.message.slice(structuredErrorPrefix.length))
      // Only overwrite with a real string. A payload without a message would
      // otherwise be coerced by the Error setter to the literal "undefined",
      // destroying the native text -- and the catch below cannot recover it,
      // because the parse succeeded.
      if (typeof details?.message === 'string') {
        error.message = details.message
      }
    } catch (_) {
      // Preserve the native message if a future payload is not understood by
      // this loader version, then attach safe diagnostic defaults below.
    }
  }

  error.kind = details?.kind
    ?? (error instanceof TypeError || requestStatusCodes.has(error.code) ? 'request' : 'engine')
  error.rookieCode = details?.rookieCode ?? null
  error.stopReason = details?.stopReason ?? null
  error.profileIds = Array.isArray(details?.profileIds) ? details.profileIds : []
  error.sourceKind = details?.sourceKind ?? null
  error.targetOs = details?.targetOs ?? null
  error.pathRedacted = details?.pathRedacted ?? false
  error.required = Array.isArray(details?.required) ? details.required : []
  return error
}

function asyncNative(nativeFunction, name) {
  requiredNative(nativeFunction, name)
  return (...args) => {
    try {
      return Promise.resolve(nativeFunction(...args)).catch((error) => {
        throw decorateNativeError(error)
      })
    } catch (error) {
      return Promise.reject(decorateNativeError(error))
    }
  }
}

const chromiumPathOptionKeys = new Set([
  'domains',
  'browserId',
  'localStatePath',
  'plaintextOnly',
  'appBound',
])

function validateChromiumPathOptions(options) {
  if (options === null || options === undefined) {
    return undefined
  }
  if (typeof options !== 'object' || Array.isArray(options)) {
    throw new TypeError('Chromium path options must be an object or null')
  }
  const prototype = Object.getPrototypeOf(options)
  if (prototype !== null && Object.getPrototypeOf(prototype) !== null) {
    throw new TypeError('Chromium path options must be a plain object or null')
  }
  for (const key of Reflect.ownKeys(options)) {
    if (typeof key !== 'string' || !chromiumPathOptionKeys.has(key)) {
      throw new TypeError(
        'Unknown Chromium path option: ' + (typeof key === 'symbol' ? key.toString() : key)
      )
    }
  }

  const normalized = {}
  const hasOwn = (key) => Object.prototype.hasOwnProperty.call(options, key)
  if (hasOwn('domains') && options.domains !== null && options.domains !== undefined) {
    if (!Array.isArray(options.domains)) {
      throw new TypeError('Chromium path option domains must be an array of strings or null')
    }
    for (const [index, domain] of options.domains.entries()) {
      if (typeof domain !== 'string') {
        throw new TypeError(
          'Chromium path option domains element ' + index + ' must be a string'
        )
      }
    }
    normalized.domains = options.domains.slice()
  }

  for (const key of ['browserId', 'localStatePath', 'appBound']) {
    if (!hasOwn(key)) {
      continue
    }
    const value = options[key]
    if (value !== null && value !== undefined) {
      if (typeof value !== 'string') {
        throw new TypeError('Chromium path option ' + key + ' must be a string or null')
      }
      normalized[key] = value
    }
  }

  if (
    hasOwn('plaintextOnly')
    && options.plaintextOnly !== null
    && options.plaintextOnly !== undefined
  ) {
    if (typeof options.plaintextOnly !== 'boolean') {
      throw new TypeError('Chromium path option plaintextOnly must be a boolean or null')
    }
    normalized.plaintextOnly = options.plaintextOnly
  }

  const selectorCount = Number(normalized.browserId !== undefined)
    + Number(normalized.localStatePath !== undefined)
    + Number(normalized.plaintextOnly === true)
  if (selectorCount > 1) {
    throw new TypeError(
      'Chromium path options browserId, localStatePath, and plaintextOnly are mutually exclusive'
    )
  }
  return normalized
}

function chromiumPathNative(nativeFunction, name) {
  const required = requiredNative(nativeFunction, name)
  return asyncNative(
    (path, options, timeoutMs, cancellation) =>
      required(path, validateChromiumPathOptions(options), timeoutMs, cancellation),
    name
  )
}

// The canonical flat path-extract job. Its options bundle `timeoutMs` as a
// field (unlike the deprecated `chromiumPathNative` family, where it is its
// own positional parameter), so it needs its own key set and validator rather
// than reusing `validateChromiumPathOptions`.
const extractFromPathOptionKeys = new Set([
  'domains',
  'browserId',
  'localStatePath',
  'plaintextOnly',
  'timeoutMs',
  'appBound',
])

const MAX_TIMEOUT_MS = 4294967295

// N-API coerces whatever JS number it is given into the native `u32` field, so
// -1, NaN, Infinity, and fractional values do not fail -- they silently become
// some other deadline than the one that was asked for. A rejected request is
// the honest answer; a 4294967295 ms timeout from `timeoutMs: -1` is not.
function validateTimeoutMs(value, functionName) {
  if (
    typeof value !== 'number'
    || !Number.isInteger(value)
    || value < 0
    || value > MAX_TIMEOUT_MS
  ) {
    throw new TypeError(
      `${functionName} option timeoutMs must be an integer between 0 and ${MAX_TIMEOUT_MS}, or null`
    )
  }
  return value
}

function validateExtractFromPathOptions(options) {
  if (options === null || options === undefined) {
    return undefined
  }
  if (typeof options !== 'object' || Array.isArray(options)) {
    throw new TypeError('extractFromPath options must be an object or null')
  }
  const prototype = Object.getPrototypeOf(options)
  if (prototype !== null && Object.getPrototypeOf(prototype) !== null) {
    throw new TypeError('extractFromPath options must be a plain object or null')
  }
  for (const key of Reflect.ownKeys(options)) {
    if (typeof key !== 'string' || !extractFromPathOptionKeys.has(key)) {
      throw new TypeError(
        'Unknown extractFromPath option: ' + (typeof key === 'symbol' ? key.toString() : key)
      )
    }
  }

  const normalized = {}
  const hasOwn = (key) => Object.prototype.hasOwnProperty.call(options, key)
  if (hasOwn('domains') && options.domains !== null && options.domains !== undefined) {
    if (!Array.isArray(options.domains)) {
      throw new TypeError('extractFromPath option domains must be an array of strings or null')
    }
    for (const [index, domain] of options.domains.entries()) {
      if (typeof domain !== 'string') {
        throw new TypeError('extractFromPath option domains element ' + index + ' must be a string')
      }
    }
    normalized.domains = options.domains.slice()
  }

  for (const key of ['browserId', 'localStatePath', 'appBound']) {
    if (!hasOwn(key)) {
      continue
    }
    const value = options[key]
    if (value !== null && value !== undefined) {
      if (typeof value !== 'string') {
        throw new TypeError('extractFromPath option ' + key + ' must be a string or null')
      }
      normalized[key] = value
    }
  }

  if (
    hasOwn('plaintextOnly')
    && options.plaintextOnly !== null
    && options.plaintextOnly !== undefined
  ) {
    if (typeof options.plaintextOnly !== 'boolean') {
      throw new TypeError('extractFromPath option plaintextOnly must be a boolean or null')
    }
    normalized.plaintextOnly = options.plaintextOnly
  }

  if (hasOwn('timeoutMs') && options.timeoutMs !== null && options.timeoutMs !== undefined) {
    normalized.timeoutMs = validateTimeoutMs(options.timeoutMs, 'extractFromPath')
  }

  const selectorCount = Number(normalized.browserId !== undefined)
    + Number(normalized.localStatePath !== undefined)
    + Number(normalized.plaintextOnly === true)
  if (selectorCount > 1) {
    throw new TypeError(
      'extractFromPath options browserId, localStatePath, and plaintextOnly are mutually exclusive'
    )
  }
  return normalized
}

function extractFromPathNative(nativeFunction, name) {
  const required = requiredNative(nativeFunction, name)
  return asyncNative(
    (path, options, cancellation) =>
      required(path, validateExtractFromPathOptions(options), cancellation),
    name
  )
}

// `allowIsolationLoss` is a decision only `jar` can act on. `read` and
// `fromPath` return a snapshot that keeps every isolated identity, so there is
// nothing there for the flag to allow -- accepting and ignoring it would be
// exactly the silent failure the fail-closed jar exists to remove. It is
// rejected by name, before any I/O, the same way an unknown extractFromPath
// option is: a request-kind TypeError carrying no rookieCode, since the fault
// is in the call rather than in anything the core classified.
function rejectAllowIsolationLoss(options, functionName) {
  if (
    options !== null
    && typeof options === 'object'
    && !Array.isArray(options)
    && Object.prototype.hasOwnProperty.call(options, 'allowIsolationLoss')
  ) {
    const error = new TypeError(
      functionName + ' does not accept allowIsolationLoss; it is a jar option. '
        + 'A snapshot keeps every isolated identity, so there is nothing to allow. '
        + 'Use jar({ ..., allowIsolationLoss: true }) for the flat projection.'
    )
    error.code = 'InvalidArg'
    throw error
  }
  return options
}

// The snapshot-returning jobs: same (options, cancellation) shape, and the
// same one option neither of them may be handed.
function snapshotNative(nativeFunction, name) {
  const required = requiredNative(nativeFunction, name)
  return asyncNative(
    (options, cancellation) => required(rejectAllowIsolationLoss(options, name), cancellation),
    name
  )
}

function unsupportedPlatform(name, supportedPlatform) {
  return () => Promise.reject(new Error(
    `${name} is only available on ${supportedPlatform}; current platform is ${platform}`
  ))
}

function platformNative(nativeFunction, name, nodePlatforms, supportedPlatform) {
  const supported = Array.isArray(nodePlatforms) ? nodePlatforms : [nodePlatforms]
  if (supported.includes(platform)) {
    requiredNative(nativeFunction, name)
    return asyncNative(nativeFunction, name)
  }
  return asyncNative(unsupportedPlatform(name, supportedPlatform), name)
}

module.exports.CancellationHandle = requiredNative(CancellationHandle, 'CancellationHandle')
module.exports.version = requiredNative(version, 'version')
module.exports.toNetscape = requiredNative(toNetscape, 'toNetscape')
module.exports.anyBrowser = asyncNative(anyBrowser, 'anyBrowser')
module.exports.extractFromPath = extractFromPathNative(extractFromPath, 'extractFromPath')
module.exports.cookiesFromPath = asyncNative(cookiesFromPath, 'cookiesFromPath')
module.exports.chromiumCookiesFromPath = chromiumPathNative(chromiumCookiesFromPath, 'chromiumCookiesFromPath')
module.exports.chromiumCookiesFromPathDetailed = chromiumPathNative(chromiumCookiesFromPathDetailed, 'chromiumCookiesFromPathDetailed')
module.exports.firefox = asyncNative(firefox, 'firefox')
module.exports.zen = asyncNative(zen, 'zen')
module.exports.librewolf = asyncNative(librewolf, 'librewolf')
module.exports.cachy = platformNative(cachy, 'cachy', 'linux', 'Linux')
module.exports.chrome = asyncNative(chrome, 'chrome')
module.exports.brave = asyncNative(brave, 'brave')
module.exports.arc = asyncNative(arc, 'arc')
module.exports.edge = asyncNative(edge, 'edge')
module.exports.opera = asyncNative(opera, 'opera')
module.exports.operaGx = platformNative(operaGx, 'operaGx', ['darwin', 'win32'], 'macOS and Windows')
module.exports.chromium = asyncNative(chromium, 'chromium')
module.exports.vivaldi = asyncNative(vivaldi, 'vivaldi')
module.exports.load = asyncNative(load, 'load')
module.exports.octoBrowser = platformNative(octoBrowser, 'octoBrowser', 'win32', 'Windows')
module.exports.internetExplorer = platformNative(internetExplorer, 'internetExplorer', 'win32', 'Windows')
module.exports.safari = platformNative(safari, 'safari', 'darwin', 'macOS')
module.exports.chromiumBased = asyncNative(chromiumBased, 'chromiumBased')
module.exports.chromiumBasedDetailed = asyncNative(chromiumBasedDetailed, 'chromiumBasedDetailed')
module.exports.firefoxProfiles = asyncNative(firefoxProfiles, 'firefoxProfiles')
module.exports.firefoxProfile = asyncNative(firefoxProfile, 'firefoxProfile')
module.exports.chromeProfiles = asyncNative(chromeProfiles, 'chromeProfiles')
module.exports.chromeProfile = asyncNative(chromeProfile, 'chromeProfile')
module.exports.firefoxBased = asyncNative(firefoxBased, 'firefoxBased')
module.exports.firefoxBasedDetailed = asyncNative(firefoxBasedDetailed, 'firefoxBasedDetailed')
module.exports.supportedBrowsers = asyncNative(supportedBrowsers, 'supportedBrowsers')
module.exports.browserProfiles = asyncNative(browserProfiles, 'browserProfiles')
module.exports.browserReport = asyncNative(browserReport, 'browserReport')
module.exports.loadReport = asyncNative(loadReport, 'loadReport')
module.exports.ReadResult = requiredNative(ReadResult, 'ReadResult')
module.exports.read = snapshotNative(read, 'read')
module.exports.jar = asyncNative(jar, 'jar')
module.exports.profiles = asyncNative(profiles, 'profiles')
module.exports.report = asyncNative(report, 'report')
module.exports.fromPath = snapshotNative(fromPath, 'fromPath')

if (testWorkerPanic) {
  module.exports.__testWorkerPanic = asyncNative(testWorkerPanic, 'testWorkerPanic')
}
