/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A cross-thread cancellation token for an in-flight extraction.
 *
 * `cancel()` is safe to call from the JS main thread while the matching
 * extraction runs on napi's worker threadpool: it flips a shared atomic
 * flag that the extraction observes at the same deadline/cancellation
 * checkpoints a `timeoutMs` budget uses, so cancellation takes effect
 * mid-extraction rather than only before it starts.
 */
export declare class CancellationHandle {
  constructor()
  /**
   * Requests cancellation. Returns `true` the first time it takes effect,
   * `false` if this handle was already cancelled.
   */
  cancel(): boolean
  get isCancelled(): boolean
}
export declare class ReadResult {
  /** Not constructible from JavaScript. Use `read()` or `fromPath()`. */
  constructor()
  get cookies(): Array<CookieObject>
  /**
   * Isolation-aware projection: the eight `Cookie` fields plus a `context`
   * object carrying CHIPS partition and Firefox container identity. Use this
   * (not `cookies`) to inventory partitions/containers -- `cookies` discards
   * that context by design.
   */
  get detailedCookies(): Array<DetailedCookieObject>
  get warnings(): Array<ReadWarningObject>
  get browserId(): string | null
  get profileId(): string | null
  /**
   * Selects the cookies `context` would send, without flattening them.
   *
   * This is **the** send-selection operation. `header` is a thin renderer
   * over it, so a collision case cannot be decided one way by `header` and
   * another way here. The returned `cookies` keep their full
   * `DetailedCookieObject` identity, and `omitted` explains what was left
   * out and why. An empty selection is a legitimate answer, not an error:
   * `omitted` is how a caller tells "no cookies at all" apart from
   * "everything was excluded".
   *
   * Throws synchronously (it reads an already-loaded snapshot) with the same
   * structured errors `header` throws.
   */
  sendView(context: string | SendContextObject): SendViewObject
  /**
   * Derives a legacy `Cookie` request-header value for `context`. A bare
   * string is sugar for `{ url: context }`: the conservative
   * (`Subresource`/`Safe`) defaults, no top-level site, no container/
   * partition selector.
   *
   * Exactly `sendView(context).header`; use `sendView` when the selected
   * records or the omission counts matter.
   *
   * A snapshot holding a CHIPS-partitioned or Firefox-container cookie
   * rejects with `incomplete_send_context` (its `required` selector names on
   * the error object) rather than silently merging isolated cookies into one
   * answer -- pass `topLevelSite` / `userContextId` / `privateBrowsingId` /
   * `firstPartyDomain` / `geckoViewSessionContextId` / `originAttributes`
   * to disambiguate.
   */
  header(context: string | SendContextObject): string
}
/** @deprecated Use `extractFromPath`. Earliest removal is 0.7. */
export declare function anyBrowser(dbPath: string, domains?: Array<string> | undefined | null, keyPath?: string | undefined | null): Promise<Array<CookieObject>>

export declare function arc(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

export declare function brave(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

/** What a registered browser claims it can do on this platform. */
export interface BrowserCapabilitiesObject {
  persistentFormats: Array<string>
  sessionFormats: Array<string>
  declaredDecryptionTiers: Array<string>
  /**
   * The declared tiers narrowed to the key providers this build actually
   * compiled and enabled.
   */
  availableDecryptionTiers: Array<string>
}

/** A browser registered for the running OS. Registration is not detection. */
export interface BrowserDescriptorObject {
  id: string
  aliases: Array<string>
  displayName: string
  engine: string
  capabilities: BrowserCapabilitiesObject
}

/**
 * Lists the discovered profiles of one registered browser.
 *
 * Rejects on an unknown `browserId`, or when every detected installation root
 * failed enumeration. A known browser with nothing installed resolves to an
 * empty array. No `appBound`: listing does no App-Bound work.
 */
export declare function browserProfiles(browserId: string, options?: ProfilesOptions | undefined | null): Promise<Array<ProfileDescriptorObject>>

/**
 * Extracts cookies from one browser as a grouped report.
 *
 * Only a bad request rejects: an unknown `browserId`, or a `profileId` this
 * browser did not yield. Extraction problems resolve as a report whose
 * `status` and `issues` describe them. `options.appBound` defaults to
 * `"injection_only"`, same as `read`.
 */
export declare function browserReport(options: BrowserReportOptions): Promise<ExtractionReportObject>

export interface BrowserReportOptions {
  browserId: string
  profileId?: string
  domains?: Array<string>
  timeoutMs?: number
  appBound?: AppBoundPolicy
}

export declare function chrome(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

/**
 * Extracts one selected Google Chrome profile as a grouped report.
 *
 * `profile` accepts the opaque ID, display name, directory name, or a full
 * path returned by `chromeProfiles` when the descriptor's
 * `profile.pathLossy` is false. A lossy path requires its opaque ID. Ambiguous
 * names reject rather than silently choosing an installation or channel.
 */
export declare function chromeProfile(profile: string, domains?: Array<string> | undefined | null): Promise<ExtractionReportObject>

/**
 * Lists Google Chrome profiles with the preferred active profile first.
 *
 * Missing, stale, or malformed activity hints retain the generic
 * default-first discovery order.
 */
export declare function chromeProfiles(): Promise<Array<ProfileDescriptorObject>>

export declare function chromium(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

/** @deprecated Use `extractFromPath`. Earliest removal is 0.7. */
export declare function chromiumCookiesFromPath(path: string, options?: ChromiumPathOptions | null, timeoutMs?: number | null, cancellation?: CancellationHandle | null): Promise<CookieObject[]>

/** @deprecated Use `fromPath(...).detailedCookies`. Earliest removal is 0.7. */
export declare function chromiumCookiesFromPathDetailed(path: string, options?: ChromiumPathOptions | null, timeoutMs?: number | null, cancellation?: CancellationHandle | null): Promise<DetailedCookieObject[]>

/** Cross-platform options for explicit Chromium cookie databases. */
export interface ChromiumPathOptions {
  domains?: string[] | null
  browserId?: string | null
  localStatePath?: string | null
  plaintextOnly?: boolean | null
  appBound?: AppBoundPolicy | null
}

/** Browser context that distinguishes partitioned/container cookies. */
export interface CookieContextObject {
  topFrameSiteKey: string | null
  hasCrossSiteAncestor: boolean | null
  sourceScheme: number | null
  sourcePort: number | null
  isPersistent: boolean | null
  originAttributes: string | null
  userContextId: number | null
  partitionKey: string | null
  privateBrowsingId: number | null
}

export interface CookieObject {
  domain: string
  path: string
  secure: boolean
  /**
   * Unix expiry time. Source values above `i64::MAX` are omitted rather than
   * wrapping into a negative JavaScript number.
   */
  expires?: number
  name: string
  value: string
  httpOnly: boolean
  sameSite: number
}

/** @deprecated Use `extractFromPath`. Earliest removal is 0.7. */
export declare function cookiesFromPath(path: string, domains?: string[] | null, timeoutMs?: number | null, cancellation?: CancellationHandle | null): Promise<CookieObject[]>

/** A cookie source a profile exposes, before any extraction is attempted. */
export interface CookieSourceDescriptorObject {
  role: string
  format: string
  path: string
  pathLossy: boolean
  /** Widened from the Rust `u16` so it arrives as an ordinary number. */
  precedence: number
}

/** Identity of the source an extraction attempted. */
export interface CookieSourceIdentityObject {
  role: string
  format: string
  path: string
  pathLossy: boolean
  /** Widened from the Rust `u16` so it arrives as an ordinary number. */
  precedence: number
}

/**
 * Cookie plus browser-specific identity context. The nested `cookie` has the
 * unchanged legacy `CookieObject` shape.
 */
export interface DetailedCookieObject {
  cookie: CookieObject
  context: CookieContextObject
}

export declare function edge(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

/**
 * Extracts cookies from one explicit cookie file as a flat, domain-filtered
 * list. The canonical flat path-extract job (Rust `extract_from_path`,
 * Python `extract_from_path`); `cookiesFromPath` / `chromiumCookiesFromPath`
 * are deprecated aliases onto this.
 *
 * Sniffs the source from its signature and schema with no credentials.
 * Portable: on Unix a Chromium database found this way is plaintext-capable
 * only (this used to probe every registered browser identity in turn); on
 * Windows a plaintext Chromium database now succeeds instead of always
 * rejecting with `missing_local_state_file`. An encrypted Chromium row
 * without an explicit credential selector is `missing_chromium_credentials`.
 * `options.appBound` defaults to `"injection_only"`, same as `read`.
 */
export declare function extractFromPath(path: string, options?: ExtractFromPathOptions | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

/**
 * Options for the canonical `extractFromPath`: `domains`; the mutually
 * exclusive `plaintextOnly` / `browserId` / `localStatePath`; `timeoutMs`;
 * `appBound`. A superset of the deprecated `ChromiumPathOptions`, which took
 * `timeoutMs` as its own positional parameter instead of a field here.
 */
export interface ExtractFromPathOptions {
  domains?: Array<string>
  browserId?: string
  localStatePath?: string
  plaintextOnly?: boolean
  timeoutMs?: number
  appBound?: AppBoundPolicy
}

/**
 * A diagnostic attached to the request, a profile, or a source.
 *
 * Repeated row-level problems are aggregated by code and stage: `occurrences`
 * counts them all while `samples` keeps a bounded excerpt.
 *
 * `use_nullable` keeps the optional context fields present and `null` rather
 * than absent, so an unset one reads the same here as the `None` Python emits
 * and the `null` the CLI's serde output emits. napi's default would omit the
 * key entirely and make Node the only surface where it disappears.
 * [`CookieObject`] deliberately keeps the default: its shape predates the
 * report DTOs and is frozen by the compatibility contract.
 */
export interface ExtractionIssueObject {
  code: string
  stage: string
  severity: string
  cause: string
  provider: string | null
  tier: string | null
  retryability: string
  occurrences: number
  samples: Array<string>
  browserId: string | null
  installationId: string | null
  profileId: string | null
  message: string
}

/**
 * A grouped extraction result.
 *
 * `issues` holds only request-wide, registry, discovery, and installation
 * problems; anything narrower is attached to its profile or source.
 */
export interface ExtractionReportObject {
  schemaVersion: number
  status: string
  termination: string
  summary: ReportStatsObject
  profiles: Array<ProfileExtractionObject>
  issues: Array<ExtractionIssueObject>
}

/**
 * Row accounting for one source or profile.
 *
 * A count that exceeded `u32` is clamped and sets `countersSaturated`.
 */
export interface ExtractionStatsObject {
  rowsSeen: number
  cookiesEmitted: number
  rowsSkipped: number
  rowsRejected: number
  providerFailures: number
  acquisitionAttempts: number
  countersSaturated: boolean
}

export declare function firefox(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

/** @deprecated Use `extractFromPath`. Earliest removal is 0.7. */
export declare function firefoxBased(dbPath: string, domains?: Array<string> | undefined | null): Promise<Array<CookieObject>>

/** Extracts cookies with Firefox container and origin context preserved. */
export declare function firefoxBasedDetailed(dbPath: string, domains?: Array<string> | undefined | null): Promise<Array<DetailedCookieObject>>

export declare function firefoxProfile(profile: string, domains?: Array<string> | undefined | null): Promise<Array<CookieObject>>

export interface FirefoxProfileObject {
  name: string
  path: string
  isDefault: boolean
}

export declare function firefoxProfiles(): Promise<Array<FirefoxProfileObject>>

/**
 * Read cookies from an explicit cookie database path.
 *
 * `options.appBound` defaults to `"injection_only"`, same as `read`.
 */
export declare function fromPath(options: FromPathOptions, cancellation?: CancellationHandle | undefined | null): Promise<ReadResult>

export interface FromPathOptions {
  path: string
  includeExpired?: boolean
  timeoutMs?: number
  browserId?: string
  /** Renamed from `keyPath` in 0.6.0 (prerelease-only, so no alias kept). */
  localStatePath?: string
  plaintextOnly?: boolean
  appBound?: AppBoundPolicy
}

/**
 * Convenience sugar for `read(options).cookies`, refusing when that flat
 * shape would silently discard isolation.
 *
 * Warnings are discarded; use `read` when they matter. JavaScript has no
 * standard cookie-jar type, so this returns the binding's language-native
 * flat `CookieObject[]` projection.
 *
 * A snapshot holding a CHIPS-partitioned or Firefox-container cookie rejects
 * with `isolation_loss_refused`, whose `required` names the same selector
 * tokens `sendView`/`header` would demand. Either name a context with
 * `read(...).sendView(...)`, or pass `allowIsolationLoss: true` to state
 * that a flat list is acceptable anyway. A snapshot with no isolated rows
 * resolves exactly as before.
 */
export declare function jar(options: JarOptions, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

/**
 * `ReadOptions` plus the one field only `jar` can honour.
 *
 * `allowIsolationLoss` is deliberately **not** on `ReadOptions`: `read`
 * returns a snapshot that keeps every isolated identity, so the flag would
 * have nothing to act on there and would be silently ignored by every
 * non-jar call that passed it.
 */
export interface JarOptions {
  browser: string
  profile?: string
  includeExpired?: boolean
  /**
   * Also includes the browser's declared session store (Gecko only; a
   * no-op elsewhere). Defaults to `false` -- **unlike 0.6-beta**, naming a
   * `profile` alone no longer imports session cookies. Omitting this on a
   * migrated 0.6-beta caller fails silently: a smaller snapshot, no error.
   */
  includeSession?: boolean
  timeoutMs?: number
  /**
   * `"disabled" | "injection_only" | "allow_elevated_fallback"`. Omitted
   * means `"injection_only"`, which recovers Chrome v20 App-Bound keys
   * without elevation. Pass `"disabled"` to skip v20 rows instead.
   */
  appBound?: AppBoundPolicy
  /**
   * Only `"legacy_first"` (the default) is representable here: a snapshot
   * or flat extract returns one answer, so there is no "every profile" for
   * `select` to name. Passing `"all"` rejects with
   * `conflicting_profile_selection` before any I/O; use `report`/
   * `browserReport` for every profile.
   */
  select?: 'legacy_first'
  /**
   * Produce the flat list even when the snapshot holds isolated rows.
   *
   * Defaults to `false`, which rejects with `isolation_loss_refused`. A flat
   * `CookieObject[]` has no cell for a CHIPS partition key, a Firefox
   * `partitionKey`, or container identity, so flattening an isolated
   * snapshot turns cookies scoped to one browsing context into cookies that
   * look like they belong everywhere. Setting this to `true` is the named
   * decision that the loss is acceptable; the output is byte-for-byte what
   * `read(...).cookies` returns.
   */
  allowIsolationLoss?: boolean
}

export declare function librewolf(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

export declare function load(domains?: Array<string> | undefined | null): Promise<Array<CookieObject>>

/**
 * Extracts cookies from every registered browser as one grouped report.
 *
 * This is the report-shaped counterpart to `load`, not a replacement: `load`
 * keeps its historical browser set and flat output. A browser that fails does
 * not abort the others; it becomes an issue on the returned report.
 * `options.appBound` defaults to `"injection_only"`, same as `read`.
 */
export declare function loadReport(options?: LoadReportOptions | undefined | null): Promise<ExtractionReportObject>

/**
 * Options for `loadReport`. Every field is optional so the whole options
 * object itself can be omitted, matching `loadReport()`'s no-argument form
 * before this PR added execution control.
 */
export interface LoadReportOptions {
  domains?: Array<string>
  timeoutMs?: number
  appBound?: AppBoundPolicy
}

export declare function opera(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

/** One discovered profile and its cookie sources. */
export interface ProfileDescriptorObject {
  profile: ProfileIdentityObject
  isDefault: boolean
  sources: Array<CookieSourceDescriptorObject>
}

/** One profile's sources, totals, and profile-scoped diagnostics. */
export interface ProfileExtractionObject {
  profile: ProfileIdentityObject
  sources: Array<SourceExtractionObject>
  stats: ExtractionStatsObject
  issues: Array<ExtractionIssueObject>
}

/**
 * Stable identity of one discovered profile.
 *
 * `profileId` is the selection key; `path` is a display value that may be
 * lossy on a non-UTF-8 filesystem, which `pathLossy` reports.
 */
export interface ProfileIdentityObject {
  browserId: string
  installationId: string
  profileId: string
  displayName: string
  path: string
  pathLossy: boolean
}

/** Alias of `browserProfiles`. No decrypt, no `appBound`. */
export declare function profiles(browserId: string, options?: ProfilesOptions | undefined | null): Promise<Array<ProfileDescriptorObject>>

/**
 * Options for `profiles` / `browserProfiles`. No `appBound`: listing does no
 * App-Bound work.
 */
export interface ProfilesOptions {
  timeoutMs?: number
}

/**
 * Unfiltered snapshot of one browser profile. Never URL-pre-sliced.
 *
 * `options.appBound` defaults to `"injection_only"`: Chrome has written
 * App-Bound (v20) cookies on Windows since Chrome 127, so refusing to
 * recover them would return an empty list for the common case. Injection is
 * unprivileged but spawns a browser process, which endpoint security can
 * flag -- pass `"disabled"` to skip v20 rows instead. Elevated SYSTEM
 * impersonation stays opt-in via `"allow_elevated_fallback"`.
 */
export declare function read(options: ReadOptions, cancellation?: CancellationHandle | undefined | null): Promise<ReadResult>

export interface ReadOptions {
  browser: string
  profile?: string
  includeExpired?: boolean
  /**
   * Also includes the browser's declared session store (Gecko only; a
   * no-op elsewhere). Defaults to `false` -- **unlike 0.6-beta**, naming a
   * `profile` alone no longer imports session cookies. Omitting this on a
   * migrated 0.6-beta caller fails silently: a smaller snapshot, no error.
   */
  includeSession?: boolean
  timeoutMs?: number
  /**
   * `"disabled" | "injection_only" | "allow_elevated_fallback"`. Omitted
   * means `"injection_only"`, which recovers Chrome v20 App-Bound keys
   * without elevation. Pass `"disabled"` to skip v20 rows instead.
   */
  appBound?: AppBoundPolicy
  /**
   * Only `"legacy_first"` (the default) is representable here: a snapshot
   * or flat extract returns one answer, so there is no "every profile" for
   * `select` to name. Passing `"all"` rejects with
   * `conflicting_profile_selection` before any I/O; use `report`/
   * `browserReport` for every profile.
   */
  select?: 'legacy_first'
}

export interface ReadWarningObject {
  code: string
  /**
   * IEEE-754; saturates at `Number.MAX_SAFE_INTEGER` rather than losing
   * precision on a Rust `u64` past that point.
   */
  count: number
  countersSaturated: boolean
  message: string
}

/**
 * Bindings name for `extract_report` / `browserReport`.
 *
 * `options.appBound` defaults to `"injection_only"`, same as `read`.
 */
export declare function report(options: ReportOptions): Promise<ExtractionReportObject>

export interface ReportOptions {
  browser: string
  profile?: string
  domains?: Array<string>
  timeoutMs?: number
  appBound?: AppBoundPolicy
  /**
   * `"legacy_first" | "all"`. Defaults to `"all"`: naming a `profile`
   * already narrows to it regardless of `select`, but `select: "all"`
   * together with `profile` is a contradiction and rejects with
   * `conflicting_profile_selection` before any I/O.
   */
  select?: 'legacy_first' | 'all'
}

/** Request-wide totals, including browsers that were registered but absent. */
export interface ReportStatsObject {
  registeredBrowsers: number
  browsersDetected: number
  browsersNotDetected: number
  installationsDiscovered: number
  profilesDiscovered: number
  sourcesSucceeded: number
  sourcesFailed: number
  rowsSeen: number
  cookiesEmitted: number
  rowsSkipped: number
  rowsRejected: number
  providerFailures: number
  countersSaturated: boolean
}

/**
 * View input for `ReadResult.header`. A bare `url` string is sugar for
 * `{ url }`; see `header`'s doc comment for why the rest matters.
 *
 * Plain `#[napi(object)]`, not `use_nullable`: this is caller-constructed
 * input (like `ReadOptions`), where every field but `url` should be
 * omittable, not merely nullable -- unlike `CookieContextObject`, which this
 * binding always populates in full and where `use_nullable` keeps every
 * field present-but-`null`.
 */
export interface SendContextObject {
  url: string
  topLevelSite?: string
  /**
   * `"navigation" | "subresource"`. Defaults to `"subresource"`, the
   * conservative choice: only a `SameSite=Lax` cross-site send depends on it.
   */
  resource?: ResourceKind
  /** `"safe" | "unsafe"`. Defaults to `"safe"`, same reasoning as `resource`. */
  method?: MethodClass
  userContextId?: number
  privateBrowsingId?: number
  /**
   * `"same_site" | "cross_site"`. Omitted means *derived*: same-site when
   * the request site is within `topLevelSite`, cross-site otherwise. Set it
   * explicitly to describe an `A -> B -> A` embed, whose request site and
   * top-level site are equal even though an ancestor frame is cross-site.
   */
  ancestorChain?: AncestorChain
  /**
   * Selects a Firefox `firstPartyDomain` origin attribute. Once supplied, a
   * row that does not carry this attribute is not a match.
   */
  firstPartyDomain?: string
  /** Selects a Firefox `geckoViewSessionContextId` origin attribute. */
  geckoViewSessionContextId?: string
  /**
   * Selects **opaque** rows by their verbatim Firefox `originAttributes`
   * suffix -- rows carrying an attribute name this build does not know, or a
   * `partitionKey` it cannot parse. Such a row is omitted from every send
   * view, and naming its stored value exactly is the only way to select it.
   * Pass the value from `context.originAttributes` rather than rebuilding
   * it: the comparison is byte equality against what the browser stored.
   */
  originAttributes?: string
  nowEpochSeconds?: number
}

/**
 * Rows a send view left out, counted by the first reason each failed.
 *
 * Every reason is always present, zeroes included, so the shape is fixed
 * across releases. A row is counted exactly once, under the first stage it
 * failed.
 */
export interface SendOmissionsObject {
  /**
   * Rows whose expiry had passed at the send-time clock. Applied regardless
   * of `includeExpired`: retaining an expired cookie in an inventory is not
   * a licence to send it.
   */
  expired: number
  /** Rows the RFC 6265 domain, path, `Secure`, or octet rules excluded. */
  notApplicable: number
  /** Rows a `SameSite` attribute excluded for this context. */
  sameSite: number
  /** Rows whose partition key or ancestor bit named a different context. */
  partition: number
  /**
   * Partitioned Chromium rows whose store predates `has_cross_site_ancestor`.
   * The bit is part of partition-key equality, so a row that never recorded
   * it is omitted rather than assumed.
   */
  ancestorChainUnknown: number
  /** Rows whose partition key no parser in this build understood. */
  unparsablePartitionKey: number
  /**
   * Rows excluded by a container or origin-attribute selector, including
   * rows carrying an origin attribute this build does not recognize.
   */
  origin: number
}

/**
 * The cookies one `SendContext` selects, before they are flattened into a
 * header string.
 */
export interface SendViewObject {
  /**
   * The selected records, in the order `header` renders them: longest path
   * first, then by name.
   */
  cookies: Array<DetailedCookieObject>
  /** The same selection rendered as a `Cookie` request-header value. */
  header: string
  /** What was left out, and why. */
  omitted: SendOmissionsObject
}

/**
 * One attempted cookie source and the cookies it produced.
 *
 * A profile-wide cookie stream is the concatenation of its `selected` sources
 * whose `status` is `succeeded`, in the order they appear. Both halves matter:
 * a source that was attempted and rejected in favour of another candidate can
 * still report `succeeded`.
 */
export interface SourceExtractionObject {
  source: CookieSourceIdentityObject
  status: string
  selected: boolean
  acquisitionStrategy: string
  cookies: Array<CookieObject>
  stats: ExtractionStatsObject
  issues: Array<ExtractionIssueObject>
}

/**
 * Lists the browsers registered for the running OS.
 *
 * Registration is not detection: a listed browser need not be installed.
 * Takes no execution control: this is a static catalog lookup with no disk
 * I/O, so there is nothing for a timeout, cancellation, or `appBound` to do.
 */
export declare function supportedBrowsers(): Promise<Array<BrowserDescriptorObject>>

/**
 * Serialize cookies in Netscape cookie-file format.
 *
 * Tabs, carriage returns, and line feeds in cookie-controlled fields are
 * encoded as `%09`, `%0D`, and `%0A`, matching the Rust, CLI, and Python APIs.
 */
export declare function toNetscape(cookies: Array<CookieObject>): string

export declare function version(): string

export declare function vivaldi(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>

export declare function zen(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>
/** rookie-cookies cross-platform facade */
export type AppBoundPolicy = 'disabled' | 'injection_only' | 'allow_elevated_fallback'
export type ResourceKind = 'navigation' | 'subresource'
export type MethodClass = 'safe' | 'unsafe'
export type AncestorChain = 'same_site' | 'cross_site'
// napi-rs v2 generated these public aliases; retain them across the v3
// generator migration so existing TypeScript imports remain source-compatible.
export type JsCancellationHandle = CancellationHandle
export type JsReadResult = ReadResult
/** Structured diagnostics attached to errors rejected by facade operations. */
export interface RookieError extends Error {
  kind: 'request' | 'stopped' | 'source' | 'engine'
  code?: string
  rookieCode: string | null
  /** Current values are timed_out, cancelled, and resource_exhausted; open for future reasons. */
  stopReason: string | null
  profileIds: string[]
  sourceKind: string | null
  targetOs: string | null
  pathRedacted: boolean
  /**
   * Selector tokens the snapshot demands: the ones incomplete_send_context
   * says a SendContext did not supply, and the ones isolation_loss_refused
   * says a flat projection would have needed. Empty for every other code.
   */
  required: string[]
}
/** Linux-only browsers */
export declare function cachy(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>
/** macOS and Windows-only browsers */
export declare function operaGx(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>
/** Windows-only browsers */
export declare function octoBrowser(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>
export declare function internetExplorer(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>
/** macOS-only browsers */
export declare function safari(domains?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, cancellation?: CancellationHandle | undefined | null): Promise<Array<CookieObject>>
/** Unix browsers */
/** @deprecated Use extractFromPath. Earliest removal is 0.7. */
export declare function chromiumBased(dbPath: string, domains?: Array<string> | undefined | null, browserId?: string | undefined | null): Promise<Array<CookieObject>>
/** @deprecated Use fromPath(...).detailedCookies. Earliest removal is 0.7. */
export declare function chromiumBasedDetailed(dbPath: string, domains?: Array<string> | undefined | null, browserId?: string | undefined | null): Promise<Array<DetailedCookieObject>>
/** Windows browsers */
/** @deprecated Use extractFromPath. Earliest removal is 0.7. */
export declare function chromiumBased(keyPath: string, dbPath: string, domains?: Array<string> | undefined | null): Promise<Array<CookieObject>>
/** @deprecated Use fromPath(...).detailedCookies. Earliest removal is 0.7. */
export declare function chromiumBasedDetailed(keyPath: string, dbPath: string, domains?: Array<string> | undefined | null): Promise<Array<DetailedCookieObject>>
